version: '3.8'

services:
  cms:
    image: wordpress:latest
    container_name: cms
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - ./wp_data:/var/www/html
    depends_on:
      - db
    networks:
      - monitoring
      - cms_net

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - monitoring
      - cms_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    networks:
      - monitoring
      - cms_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./GAP-1/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./GAP-1/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./GAP-1/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: -nginx.scrape-uri=http://nginx:8080/stub_status
    ports:
      - "9113:9113"
    networks:
      - monitoring
    depends_on:
      - nginx

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    networks:
      - monitoring

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - 9115:9115
    networks:
      - monitoring

  mysql_exporter:
    image: prom/mysqld-exporter:v0.12.1
    container_name: mysql_exporter
    environment:
      DATA_SOURCE_NAME: "root:root_password@tcp(db:3306)/"
    ports:
      - "9104:9104"
    networks:
      - monitoring
    depends_on:
      db:
        condition: service_healthy

networks:
  monitoring:
  cms_net: