global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-warning'  # Specify a default receiver
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
    - match:
        severity: warning
      receiver: 'telegram-warning'

receivers:
  - name: 'telegram-critical'
    telegram_configs:
      - send_resolved: true
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: 416835955
        message: |
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}

  - name: 'telegram-warning'
    telegram_configs:
      - send_resolved: true
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: 416835955
        message: |
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'instance']