global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match:
        severity: critical
      receiver: telegram

    - match:
        severity: warning
      receiver: slack

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'https://webhook.site/51b8ccfe-9492-4507-afb7-0536a2bb146b'

  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        bot_token: ${TELEGRAM_BOT_TOKEN}  # Use environment variable
        #chat_id: ${TELEGRAM_CHAT_ID}
        chat_id: 416835955 # ${TELEGRAM_CHAT_ID} variable is being treated as a string, but it needs to be an integer (int64). Keep number
        message: '{{ template "telegram.default.message" . }}'

  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'  # Use environment variable
        #api_url_secret: '${SLACK_API_URL_SECRET}'  # Use environment variable
        channel: '#alertmanager'
        text: '{{ template "slack.default.message" . }}'

templates:
  - '/etc/alertmanager/custom.tmpl'
