global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://172.19.0.6:80  # Replace with your CMS IP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask_app:5000'] 

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091'] 
