global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 5s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  external_labels:
    environment: prometheus-demo

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - '172.19.0.18:9100'  # Node Exporter

  - job_name: mysql_exporter
    static_configs:
      - targets: ['172.19.0.20:9104']  # MySQL Exporter

  - job_name: nginx_exporter
    static_configs:
      - targets: ['172.19.0.17:9113']  # NGINX Exporter
  
  - job_name: grafana
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['172.19.0.16:3000']  # Grafana

  - job_name: alertmanager
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['172.19.0.14:9093']  # Alertmanager

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://172.19.0.10:80  # CMS
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.19.0.19:9115  # Blackbox Exporter

  - job_name: flask_app
    metrics_path: /metrics
    static_configs:
      - targets: ['172.19.0.21:5000']  # Flask App

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['172.19.0.15:9091']  # Pushgateway

  - job_name: viktoria_metrics
    static_configs:
      - targets: ['172.19.0.22:8428']  # Victoria Metrics

remote_write:
  - url: "http://172.19.0.22:8428/api/v1/write"  # Victoria Metrics
    write_relabel_configs:
      - source_labels: [__address__]
        target_label: site
        replacement: 'prod'
